# Writing and reading CSV

`mammos_entity` can write and read an `EntityCollection` in CSV format with a custom metadata block at the top of the file. Details of the file format are explained in the {func}`mammos_entity.EntityCollection.to_csv` API reference. CSV only supports tabular data. Therefore, an `EntityCollection` can only be saved to CSV if its data is tabular, i.e. all contained entity-likes are one-dimensional and have the same length.

In [1]:
from pathlib import Path

import mammos_units as u

import mammos_entity as me

## Writing

We create some artificial data that we can write to file:

In [2]:
collection = me.EntityCollection(
    "Example description.\nThe description can have multiple lines.\n\nLines can also be empty.",
    Ms=me.Ms([600, 650, 700], "kA/m", description="Evaluated using UppASD with 70000 Monte Carlo steps."),
    T=me.T([1, 2, 3], "K"),
    theta_angle=[0, 0.5, 0.7] * u.rad,
    comp=me.Entity("ChemicalComposition", ["Nd2Fe14B", "Nd2Fe14B", "Nd2Fe14B"]),
    demag_factor=me.Entity("DemagnetizingFactor", [1 / 3, 1 / 3, 1 / 3]),
    comments=["Some comment", "Some other comment", "A third comment"],
)
collection

EntityCollection(
    description='Example description.\nThe description can have multiple lines.\n\nLines can also be empty.',
    Ms=QuantityEntity(ontology_label='SpontaneousMagnetization', value=array([600., 650., 700.]), unit='kA / m', description='Evaluated using UppASD with 70000 Monte Carlo steps.'),
    T=QuantityEntity(ontology_label='ThermodynamicTemperature', value=array([1., 2., 3.]), unit='K'),
    theta_angle=<Quantity [0. , 0.5, 0.7] rad>,
    comp=StringEntity(ontology_label='ChemicalComposition', value=array(['Nd2Fe14B', 'Nd2Fe14B', 'Nd2Fe14B'], dtype=StringDType())),
    demag_factor=QuantityEntity(ontology_label='DemagnetizingFactor', value=array([0.33333333, 0.33333333, 0.33333333])),
    comments=['Some comment', 'Some other comment', 'A third comment'],
)

We can write data to a csv file as shown in the following cell:

In [3]:
collection.to_csv("example.csv")

This has produced the following file which contains the `EntityCollection` description along with Entity and unit information for each column of the csv.

In [4]:
print(Path("example.csv").read_text())

# mammos csv v3
#----------------------------------------
# Example description.
# The description can have multiple lines.
#
# Lines can also be empty.
#----------------------------------------
SpontaneousMagnetization,ThermodynamicTemperature,,ChemicalComposition,DemagnetizingFactor,
Evaluated using UppASD with 70000 Monte Carlo steps.,,,,,
https://w3id.org/emmo/domain/magnetic-materials#EMMO_032731f8-874d-5efb-9c9d-6dafaa17ef25,https://w3id.org/emmo#EMMO_affe07e4_e9bc_4852_86c6_69e26182a17f,,https://w3id.org/emmo#EMMO_7efd64d1_05a1_49cd_a7f0_783ca050d4f3,https://w3id.org/emmo/domain/magnetic-materials#EMMO_0f2b5cc9-d00a-5030-8448-99ba6b7dfd1e,
kA / m,K,rad,,,
Ms,T,theta_angle,comp,demag_factor,comments
600.0,1.0,0.0,Nd2Fe14B,0.3333333333333333,Some comment
650.0,2.0,0.5,Nd2Fe14B,0.3333333333333333,Some other comment
700.0,3.0,0.7,Nd2Fe14B,0.3333333333333333,A third comment

## Reading
We can read it back in to recreate the original `EntityCollection`:

In [5]:
content = me.from_csv("example.csv")
content

EntityCollection(
    description='Example description.\nThe description can have multiple lines.\n\nLines can also be empty.',
    Ms=QuantityEntity(ontology_label='SpontaneousMagnetization', value=array([600., 650., 700.]), unit='kA / m', description='Evaluated using UppASD with 70000 Monte Carlo steps.'),
    T=QuantityEntity(ontology_label='ThermodynamicTemperature', value=array([1., 2., 3.]), unit='K'),
    theta_angle=<Quantity [0. , 0.5, 0.7] rad>,
    comp=StringEntity(ontology_label='ChemicalComposition', value=array(['Nd2Fe14B', 'Nd2Fe14B', 'Nd2Fe14B'], dtype=StringDType())),
    demag_factor=QuantityEntity(ontology_label='DemagnetizingFactor', value=array([0.33333333, 0.33333333, 0.33333333])),
    comments=<StringArray>
['Some comment', 'Some other comment', 'A third comment']
Length: 3, dtype: str,
)

As shown in the [`EntityCollection` notebook](entity-collection.ipynb) we can access the individual elements of the collection:

In [6]:
content.Ms

QuantityEntity(ontology_label='SpontaneousMagnetization', value=array([600., 650., 700.]), unit='kA / m', description='Evaluated using UppASD with 70000 Monte Carlo steps.')

In [7]:
content.theta_angle

We can also get a `pandas` dataframe of the data we have read. Here, we choose to include units it the column names:

In [8]:
content.to_dataframe(include_units=True)

,Ms (kA / m),T (K),theta_angle (rad),comp,demag_factor,comments
0,600.0,1.0,0.0,Nd2Fe14B,0.333333,Some comment
1,650.0,2.0,0.5,Nd2Fe14B,0.333333,Some other comment
2,700.0,3.0,0.7,Nd2Fe14B,0.333333,A third comment

## Reading with `pandas`
We recommend to read these files using `mammos_entity` however the data can be read directly using other packages such as `pandas`. However, we can only conveniently load the values and not the ontology or unit information. We can use the `header` argument to point at the line number of the header. The function `pandas.read_csv` uses the `header` line to get column headers and reads everything following it as data. Note that the number of header lines changes depending on the length of the collection description. Reading with mammos-entity and then converting to a dataframe is therefore preferable.

In [9]:
import pandas as pd

pd.read_csv("example.csv", header=11)

      Ms    T  theta_angle      comp  demag_factor            comments
0  600.0  1.0          0.0  Nd2Fe14B      0.333333        Some comment
1  650.0  2.0          0.5  Nd2Fe14B      0.333333  Some other comment
2  700.0  3.0          0.7  Nd2Fe14B      0.333333     A third comment